[package]
name = "example"
version = "0.1.37-alpha.0"
authors = ["Walfie <walfington@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reqwest = "0.11.4"
tokio = { version = "1.11.0", features = ["full"] }
