name: Rust

on: [push, pull_request]

jobs:
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install clippy
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy --all

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install clippy
      run: rustup component add rustfmt
    - name: Run rustfmt
      run: cargo fmt --all -- --check

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose

