name: Test Nix
on: [pull_request]

jobs:
  test:
    name: Test Nix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Install nixUnstable
      run: nix-env -iA nixpkgs.nixUnstable
    - run: nix build

